pipeline {
    agent any

    tools {
        maven 'Maven3'        // Jenkins Maven tool name
        jdk 'Java11'          // Jenkins JDK tool name
    }

    environment {
        SONAR_PROJECT_KEY = "java-hello-jar"
        SONAR_PROJECT_NAME = "Java Hello JAR"
    }

    stages {

        stage('Checkout Code from GitHub') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/swetha-200160/java-project.git'
            }
        }

        stage('SonarQube Code Analysis') {
            steps {
                withSonarQubeEnv('SonarQubeServer') {   // Jenkins Sonar server name
                    sh """
                    mvn sonar:sonar \
                    -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                    -Dsonar.projectName='${SONAR_PROJECT_NAME}'
                    """
                }
            }
        }

        stage('Build JAR Package') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Run JAR on Server') {
            steps {
                sh '''
                # Stop previous process
                pkill -f "hello-jar-1.0.0.jar" || true

                # Run new JAR in background
                nohup java -jar target/hello-jar-1.0.0.jar > app.log 2>&1 &
                '''
            }
        }
    }
}
